name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2233
          script: |
            echo "Navigating to deployment directory..."
            cd /github/rabbit-log-puller            
            echo "Pulling latest code from Git..."
            git pull
            
            cd /github
            echo "Rebuilding and restarting the rabbitmq-puller service..."
            # The --build flag forces a rebuild on the server
            # The --no-deps flag ensures only this service is affected
            docker compose up -d --build --no-deps rabbitmq-puller